In [1]:
import numpy as np

In [2]:
x = np.random.random((3, 3, 3))
print(x)

[[[8.34221145e-02 3.49533126e-01 7.66596319e-02]
  [4.93058348e-01 1.99325026e-01 6.45994876e-01]
  [1.54294311e-01 4.84088580e-01 8.75019906e-01]]

 [[4.02885823e-01 3.38508717e-02 3.26691287e-01]
  [9.19365066e-01 5.37029783e-01 6.85783866e-01]
  [7.24172072e-01 6.43793717e-02 1.27678708e-01]]

 [[9.86479478e-01 9.08858310e-01 5.88074410e-01]
  [5.28835344e-01 9.75834847e-02 3.52256426e-01]
  [5.75204792e-05 4.45936907e-01 5.56569992e-01]]]
