In [2]:
import numpy as np

In [3]:
x = np.random.random((2, 3, 4))
print(x)

[[[0.68480098 0.81874488 0.0331396  0.74127281]
  [0.60443064 0.72113304 0.80086755 0.05952291]
  [0.15537745 0.21934284 0.7987467  0.89280257]]

 [[0.34754113 0.62049658 0.30563253 0.14285843]
  [0.08220014 0.06341926 0.51739674 0.72672197]
  [0.50219863 0.09716364 0.85658889 0.80920839]]]
